#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run from the repo root regardless of where the script is invoked.
cd "$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE=".env.local"

TOTAL_STAGES=7

banner "Padelboys — push notifications (#9) setup"

# ── Stage 1: VAPID keypair ─────────────────────────────────────────────────
stage "Generate a VAPID keypair"
say "Web Push needs a VAPID keypair so the Edge Functions can sign pushes."
say "The private key must never reach the browser or git — only Supabase's"
say "server-side secrets store holds it."
step "Run this in another terminal (or let it run below), then copy both keys:"
say "    npx web-push generate-vapid-keys"
if confirm "Run it now from here?"; then
  npx --yes web-push generate-vapid-keys || warn "npx failed — run it manually and paste the keys below."
fi
ask VAPID_PUBLIC_KEY "Paste the Public Key:"
ask_secret VAPID_PRIVATE_KEY "Paste the Private Key:"
ask VAPID_SUBJECT "Contact email for push services (mailto:you@example.com):"

# ── Stage 2: link the Supabase CLI to the project ──────────────────────────
stage "Supabase CLI — login + link"
SUPABASE_URL_CURRENT=$(_existing VITE_SUPABASE_URL || true)
PROJECT_REF=$(printf '%s' "$SUPABASE_URL_CURRENT" | sed -E 's#https://([^.]+)\.supabase\.co.*#\1#')
say "The CLI needs to be logged in and linked to push migrations and deploy"
say "the two new Edge Functions."
if [[ -n "$PROJECT_REF" ]]; then
  note "Detected project ref from .env.local: $PROJECT_REF"
else
  warn "Couldn't read VITE_SUPABASE_URL from .env.local — run scripts/setup-supabase.sh first."
fi
step "Browser login (approve the CLI request that opens):"
npx supabase login || warn "login failed or was skipped — re-run this stage later."
if [[ -n "$PROJECT_REF" ]]; then
  printf '  %sProject ref%s [Enter keeps %s] ' "$BOLD" "$RESET" "$PROJECT_REF"
else
  printf '  %sProject ref to link:%s ' "$BOLD" "$RESET"
fi
read -r SUPABASE_PROJECT_REF || true
[[ -z "$SUPABASE_PROJECT_REF" ]] && SUPABASE_PROJECT_REF="$PROJECT_REF"
if [[ -n "$SUPABASE_PROJECT_REF" ]]; then
  npx supabase link --project-ref "$SUPABASE_PROJECT_REF" || warn "link failed — check the ref and try again."
else
  warn "no project ref available — skipped linking, do it manually: supabase link --project-ref <ref>"
fi

# ── Stage 3: push the new migrations ───────────────────────────────────────
stage "Apply the new migrations"
say "Adds the push_subscriptions table, game_nights.created_by, the"
say "on-insert trigger that pushes when a night is planned, and the pg_cron"
say "schedule for the morning reminder. Safe to re-run — only new migrations"
say "get applied."
if confirm "Run 'supabase db push' now?"; then
  npx supabase db push || warn "db push failed — check the CLI output above."
else
  SKIPPED+=("supabase db push (run it manually)")
fi

# ── Stage 4: Edge Function secrets ─────────────────────────────────────────
stage "Set the Edge Function secrets"
say "VAPID keys live server-side only — set as Supabase function secrets,"
say "never as VITE_ variables (those ship to the browser bundle)."
npx supabase secrets set \
  "VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY" \
  "VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY" \
  "VAPID_SUBJECT=$VAPID_SUBJECT" \
  && printf '  %s✓ set%s VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT\n' "$GREEN" "$RESET" \
  || warn "secrets set failed — re-run: supabase secrets set VAPID_PUBLIC_KEY=... VAPID_PRIVATE_KEY=... VAPID_SUBJECT=..."

# ── Stage 5: deploy the Edge Functions ─────────────────────────────────────
stage "Deploy the Edge Functions"
say "Both keep default JWT verification ON: notify-night-planned is called"
say "by a Postgres trigger on game_nights insert, game-day-reminder by"
say "pg_cron — both authenticate with the service-role key from Vault"
say "(stage 7), which is already a valid Supabase JWT."
npx supabase functions deploy notify-night-planned || warn "deploy failed for notify-night-planned"
npx supabase functions deploy game-day-reminder || warn "deploy failed for game-day-reminder"

# ── Stage 6: frontend public key ───────────────────────────────────────────
stage "Frontend VAPID public key"
say "The public key is safe in the browser — it only lets a device create a"
say "push subscription, never read or send one."
write_env VITE_VAPID_PUBLIC_KEY "$VAPID_PUBLIC_KEY"
if command -v vercel >/dev/null 2>&1; then
  if confirm "Also set VITE_VAPID_PUBLIC_KEY on Vercel (production + preview)?"; then
    printf '%s' "$VAPID_PUBLIC_KEY" | vercel env add VITE_VAPID_PUBLIC_KEY production || warn "vercel env add (production) failed"
    printf '%s' "$VAPID_PUBLIC_KEY" | vercel env add VITE_VAPID_PUBLIC_KEY preview || warn "vercel env add (preview) failed"
  else
    SKIPPED+=("Vercel env VITE_VAPID_PUBLIC_KEY (production + preview)")
  fi
else
  note "Vercel CLI not found — add it by hand:"
  note "  Vercel dashboard → padelboys → Settings → Environment Variables"
  note "  VITE_VAPID_PUBLIC_KEY = $VAPID_PUBLIC_KEY  (Production + Preview)"
  SKIPPED+=("Vercel env VITE_VAPID_PUBLIC_KEY (production + preview)")
fi

# ── Stage 7: Vault secrets for the DB-side push calls ──────────────────────
stage "Vault secrets for the night-planned trigger + reminder cron"
say "Both push events are fired from Postgres itself (a trigger on"
say "game_nights insert, and a daily pg_cron job) rather than from the"
say "browser, so delivery doesn't depend on a phone's tab staying open."
warn "service_role_key bypasses every RLS policy — paste it only into this"
warn "one SQL editor tab, never into the app, a chat, or a .env file."
PROJECT_URL="https://${SUPABASE_PROJECT_REF:-$PROJECT_REF}.supabase.co"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF:-$PROJECT_REF}/sql/new"
step "Settings → API Keys → copy the 'service_role' key (NOT anon)."
say "Paste and run this in the SQL editor tab that just opened, replacing"
say "<service_role key> with the value you just copied:"
printf '\n    select vault.create_secret(%s, %s);\n' "'$PROJECT_URL'" "'project_url'"
printf '    select vault.create_secret(%s, %s);\n\n' "'<service_role key>'" "'service_role_key'"
pause "Ran both statements successfully? Press Enter."
note "Verify any time with: select * from cron.job where jobname = 'game-day-reminder';"

finish
say "Verify end to end: plan a night from one device/browser (Notification"
say "permission granted, PWA installed to the home screen if on iOS ≥16.4)"
say "and confirm a second logged-in device receives the push."
say "For the reminder, check the schedule fired via:"
say "  select * from cron.job_run_details order by start_time desc limit 5;"
