-- Player-drawn avatars: replaces picking a fixed species with an 8x6 pixel
-- editor (see src/lib/pixels.js). One row of 48 characters, one per cell:
-- '.' is transparent, any other character is an index into PALETTE.
--
-- Rows 6-7 of the 8x8 viewBox stay reserved for the accent band, which is why
-- the grid is 8x6 and the string is 48 and not 64 characters.
--
-- Backfilled from each player's current species art so nobody's avatar changes
-- on migration. The strings below were generated by avatarFromSpecies() and
-- verified to decode back to the exact same pixels (zero colour drift).
--
-- species stays on the table: it no longer drives rendering, but Avatar.jsx
-- falls back to it whenever avatar is null, so a row inserted later without a
-- drawing still renders something.

alter table players add column avatar text;

update players set avatar = '11111111111111111105501111555511115ss511.111111.' where id = 'da211d0c-e128-4a58-9f1c-dbb075dff486';
update players set avatar = '.o....o..pppppp..q0qq0q..qqqqqq..qrrrrq...r00r..' where id = 'c5e45cc8-615f-4cd9-92d5-183ecae6ea7b';
update players set avatar = '.o....o..pppppp..q0qq0q..qqqqqq..qrrrrq...r00r..' where id = 'daac5abc-c957-4787-807e-a684600804bc';
update players set avatar = '..wwww..xxxxxxxx.w0wwww..wwwwwss.wwwwww..xxxxxx.' where id = '04449891-601d-47bb-b975-4b52fbbd8df4';
update players set avatar = 'ccggggcc.gggggg..kkkkkk..k0kk0k..kkkkkk..kkcckk.' where id = 'abb5f2b8-406e-4d24-a3c1-76939d6dc4ee';
update players set avatar = '1155551155555555.115511..115511..555555..551155.' where id = '9129332f-7783-4a73-9dbe-a325d5853d5b';
update players set avatar = 'eeeeeeeeeeeeeeee.888888..808808..888888..88ll88.' where id = '7ec1cb3b-3ae6-4727-bcd8-66579ed15a7a';

-- 48 characters, each '.' or a base62 palette index. Nullable on purpose: a
-- new player has no drawing until they make one.
alter table players add constraint players_avatar_check
  check (avatar is null or avatar ~ '^[.0-9a-zA-Z]{48}$');

grant update (avatar) on players to anon, authenticated;
